### ISSUE TITLE
FTP Timeout error on LIST Directory

### ISSUE THREAD

**Issue by voxsoftware** [trs/ftp-srv#59] opened 2017-12-05 05:41 UTC
Ubuntu 16.04 64 bits
Listing directory not works, this shows the console: 
```javascript
{"name":"ftp-srv","hostname":"vps0","pid":22478,"id":"318b90e8-1643-4b61-9290-72a5d554f7ce","ip":null,"directive":"LIST","level":50,"err":{"message":"timed out after 5000ms","name":"TimeoutError","stack":"TimeoutError: timed out after 5000ms\n    at onTimeout (/home/kodhe/projects/ftp-server/node_modules/when/lib/decorators/timed.js:69:7)\n    at Timeout._onTimeout (/home/kodhe/projects/ftp-server/node_modules/when/lib/decorators/timed.js:13:4)\n    at ontimeout (timers.js:386:11)\n    at tryOnTimeout (timers.js:250:5)\n    at Timer.listOnTimeout (timers.js:214:5)"},"msg":"timed out after 5000ms","time":"2017-12-05T05:29:00.119Z","v":0}
```

**Comment by trs** [comment] 2017-12-06 03:47
This is most likely caused by the client not being able to establish a passive connection to one of the pasv ports.

**Comment by trs** [comment] 2017-12-09 00:41
I'm going to close this as I feel it is most likely a port issue.

Feel free to comment if you have further issues.

**Closed by trs** 2017-12-09 00:41 UTC

**Comment by DiegoRBaquero** [comment] 2018-05-30 02:44
@trs I'm running the server inside a docker instance, which is behind nginx reverse proxy, which is behind a load balancer.

I set the passive range to 8000-8001 and opened both ports. I can telnet to both. However, it doesn't work. I tried setting the pasv_url as 127.0.0.1 and the load balancer url, but neither worked. 

Would realllly appreciate any help you could provide me.

**Comment by trs** [comment] 2018-05-30 16:09
It times out because it does not receive a connection to the passive listener.

If you're connecting externally, you'll need to pass the client your external IP. Since this is the IP they use to establish a connection.
This is done with the `pasv_url` option. (Provide `0.0.0.0` to `pasv_url` for your external IP to be [found automatically](https://github.com/trs/ftp-srv/blob/master/src/helpers/resolve-host.js).

**Comment by DiegoRBaquero** [comment] 2018-05-30 19:41
When I provided 0.0.0.0, it passed the external IP of the client (?). When doing 127.0.0.1, Filezilla used the current server's IP and it worked.

Thank you!

**Comment by trs** [comment] 2018-05-30 19:45
Passing `0.0.0.0` to `pasv_url` will get the external IP of the server, and send that to the client in response to `PASV`.

Glad it worked!

**Comment by rainerCH** [comment] 2019-08-06 08:24
Hi @trs 
i appreciate your work on ftp-srv :)
is it possible to catch these kind of errors? how?
thank you!

**Comment by guidouil** [comment] 2019-10-31 13:29
Hello @trs, I have the exact same error after updating to latest
Maybe I'm missing something, here is my starting conf
```
const ftpServer = new FtpSrv({
    url: `ftp://0.0.0.0:${Meteor.settings.public.ftpPort}`,
    pasv_url: '0.0.0.0',
    pasv_min: Meteor.settings.ftpPasvMin,
    pasv_max: Meteor.settings.ftpPasvMax,
    greeting: 'Welcome to Torrents Duck FTP server',
    tls: false,
    anonymous: false,
    file_format: 'ls',
    timeout: 60000,
  });
```
I get the connection but same it dies on this message 
```
{"name":"ftp-srv","hostname":"cmapage-FTP","pid":1,"id":"2889cd19-8fb5-4b33-a8e1-7e3b25358f1d","directive":"LIST","level":50,"err":{"message":"operation timed out","name":"TimeoutError","stack":"TimeoutError: operation timed out\n    at afterTimeout (/built_app/programs/server/npm/node_modules/bluebird/js/release/timers.js:46:19)\n    at Timeout.timeoutTimeout [as _onTimeout] (/built_app/programs/server/npm/node_modules/bluebird/js/release/timers.js:76:13)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)"},"msg":"operation timed out","time":"2019-10-31T13:22:20.440Z","v":0}
```

Can you please help

**Comment by d1y** [comment] 2019-11-20 09:21
> @guidouil `0.0.0.0` no longer resolves your external IP. You'll have to use something like [`public-ip`](https://www.npmjs.com/package/public-ip) to resolve it.
> 
> ```js
> const pasv_url = await publicIp.v4();
> 
> const ftpServer = new FtpSrv({
>    pasv_url,
>    ...
> });
> ```

Thank you. I am in the LAN, all the network segments that I want to fill in are LAN. I use https://github.com/sindresorhus/public-ip

**Comment by adharsh05** [comment] 2020-12-01 10:26
@trs: I connected through 0.0.0.0. works good in local docker environment. When connected through different network. It timeout. One more thing,  what is the need for const pasv_url = await publicIp.v4();. When need to use this?.
When connected through Dev environment, it got timeout. Please suggest and help in this.

**Comment by adharsh05** [comment] 2020-12-02 11:09
@guidouil: After changing to pasv_url: require('public-ip').ipv4(), is that work for external ip and multiple client request?

**Comment by mcfriend99** [comment] 2022-03-02 11:03
I am still having this issue and the `public-ip` fix isn't working for me.
